name: Security

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

permissions: {}

jobs:
  security:
    name: Security / aggregate
    permissions:
      contents: read
      pull-requests: read
    uses: otedesco/gh-action-templates/.github/workflows/security.yml@dee28264b5f99ed00e72f1f017e952e3e83b74b3 # OPS-186 merged central security workflow
